config/routes.rb
Rails.application.routes.draw do
  resources :minors
  default_url_options host: 'localhost:3000'

  namespace :api do
    resources :services, only: [:index, :show]
  end

  resources :services

  get 'welcome/index'
  root 'minors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/minor.rb
class Minor < ApplicationRecord
  validates :city, presence: true
  validates :faculty, presence: true
  validates :name, presence: true
  validates :page_url, presence: true
end

app/models/service.rb
class Service < ApplicationRecord

  def as_json_for_main_page
    {
      title: title,
      description: description,
      requirements: requirements,
      duration: duration,
      correction_time: correction_time
    }
  end

end

app/controllers/api/services_controller.rb
class Api::ServicesController < ApplicationController
  def index
    services = Service.all.collect
    services_data = []

    services.each do |service|
      service_data = service.as_json_for_main_page
      service_data[:url] = api_service_url(service)
      services_data << service_data
    end

    render json: services_data
  end

  def show
    service = Service.find(params[:id])
    service_data = service.as_json_for_main_page
    service_data[:url] = api_service_url(service)

    render json: service_data
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/minors_controller.rb
class MinorsController < ApplicationController
  before_action :set_minor, only: [:show, :edit, :update, :destroy]

  # GET /minors
  # GET /minors.json
  def index
    @minors = Minor.all
    # @cities = @minors.collect { |minor| minor.city }.uniq
  end

  # GET /minors/1
  # GET /minors/1.json
  def show
  end

  # GET /minors/new
  def new
    @minor = Minor.new
  end

  # GET /minors/1/edit
  def edit
  end

  # POST /minors
  # POST /minors.json
  def create
    @minor = Minor.new(minor_params)

    respond_to do |format|
      if @minor.save
        format.html { redirect_to @minor, notice: 'Minor was successfully created.' }
        format.json { render :show, status: :created, location: @minor }
      else
        format.html { render :new }
        format.json { render json: @minor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minors/1
  # PATCH/PUT /minors/1.json
  def update
    respond_to do |format|
      if @minor.update(minor_params)
        format.html { redirect_to @minor, notice: 'Minor was successfully updated.' }
        format.json { render :show, status: :ok, location: @minor }
      else
        format.html { render :edit }
        format.json { render json: @minor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minors/1
  # DELETE /minors/1.json
  def destroy
    @minor.destroy
    respond_to do |format|
      format.html { redirect_to minors_url, notice: 'Minor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minor
      @minor = Minor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def minor_params
      params.require(:minor).permit(:city, :faculty, :name, :page_url)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:title, :description, :requirements, :duration, :correction_time)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api/services_helper.rb
module Api::ServicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/minors_helper.rb
module MinorsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ADCKarma</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/minors/_form.html.erb
<%= form_with(model: minor, local: true) do |form| %>
  <% if minor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(minor.errors.count, "error") %> prohibited this minor from being saved:</h2>

      <ul>
        <% minor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :faculty %>
    <%= form.text_field :faculty %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :page_url %>
    <%= form.text_field :page_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/minors/edit.html.erb
<h1>Editing Minor</h1>

<%= render 'form', minor: @minor %>

<%= link_to 'Show', @minor %> |
<%= link_to 'Back', minors_path %>

app/views/minors/index.html.erb
<h2>Москва</h2>

<% @minors.each do |minor| %>
  <% if minor.city == 'Москва' %>
    <p><%= link_to minor.name, minor.page_url %></p>
  <% end %>
<% end %>

<h2>Санкт-Петербург</h2>

<% @minors.each do |minor| %>
  <% if minor.city == 'Санкт-петербург' %>
    <p><%= link_to minor.name, minor.page_url %></p>
  <% end %>
<% end %>

<h2>Нижний Новгород</h2>

<% @minors.each do |minor| %>
  <% if minor.city == 'Нижний Новгород' %>
    <p><%= link_to minor.name, minor.page_url %></p>
  <% end %>
<% end %>

<h2>Пермь</h2>

<% @minors.each do |minor| %>
  <% if minor.city == 'Пермь' %>
    <p><%= link_to minor.name, minor.page_url %></p>
  <% end %>
<% end %>

app/views/minors/index_old.html.erb
<p id="notice"><%= notice %></p>

<h1>Minors</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Faculty</th>
      <th>Name</th>
      <th>Page url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @minors.each do |minor| %>
      <tr>
        <td><%= minor.city %></td>
        <td><%= minor.faculty %></td>
        <td><%= minor.name %></td>
        <td><%= minor.page_url %></td>
        <td><%= link_to 'Show', minor %></td>
        <td><%= link_to 'Edit', edit_minor_path(minor) %></td>
        <td><%= link_to 'Destroy', minor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Minor', new_minor_path %>

app/views/minors/new.html.erb
<h1>New Minor</h1>

<%= render 'form', minor: @minor %>

<%= link_to 'Back', minors_path %>

app/views/minors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @minor.city %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @minor.faculty %>
</p>

<p>
  <strong>Name:</strong>
  <%= @minor.name %>
</p>

<p>
  <strong>Page url:</strong>
  <%= @minor.page_url %>
</p>

<%= link_to 'Edit', edit_minor_path(@minor) %> |
<%= link_to 'Back', minors_path %>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :requirements %>
    <%= form.text_area :requirements %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :correction_time %>
    <%= form.number_field :correction_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Requirements</th>
      <th>Duration</th>
      <th>Correction time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.title %></td>
        <td><%= service.description %></td>
        <td><%= service.requirements %></td>
        <td><%= service.duration %></td>
        <td><%= service.correction_time %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @service.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @service.requirements %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @service.duration %>
</p>

<p>
  <strong>Correction time:</strong>
  <%= @service.correction_time %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<script type="text/javascript">
  fetch('http://localhost:3000/api/services', {
    headers: {
      'Content-Type': 'application/json',
    }
  })
    .then(response => response.json())
    .then(data => {
      console.log(data)
      document.body.append(JSON.stringify(data))
    })
</script>